{
 "title": "Heat Pump",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ambient Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 } },
  {
   "title": "Last Ambient Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heat_pump_ambient_temperature", "legendFormat": "Ambient Temperature" }
   ]
  },
  {
   "title": "Max. Amb. Temp.",
   "type": "stat",
   "description": "Maximum Ambient Temperature",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(heat_pump_ambient_temperature[$__range])",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Min. Amb. Temp.",
   "type": "stat",
   "description": "Minimum  Ambient Temperature",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(heat_pump_ambient_temperature[$__range])",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Last Room Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heat_pump_current_room_temperature",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Max. Room Temp.",
   "type": "stat",
   "description": "Maximum Room Temperature",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(heat_pump_current_room_temperature[$__range])",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Min. Room Temp.",
   "type": "stat",
   "description": "Maximum Room Temperature",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(heat_pump_current_room_temperature[$__range])",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  { "title": "Underfloor Heating", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "heat_pump_return_temperature" },
    {
     "expr": "heat_pump_input_heat_source_temperature"
    }
   ]
  },
  {
   "title": "Domestic Hot Water Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "heat_pump_return_temperature", "legendFormat": "Return Temperature" },
    { "expr": "heat_pump_flow_temperature", "legendFormat": "Flow Temperature" },
    {
     "expr": "heat_pump_input_heat_source_temperature",
     "legendFormat": "Input Heat Source Temperature"
    },
    {
     "expr": "heat_pump_current_room_temperature",
     "legendFormat": "Room Temperature"
    }
   ]
  },
  { "title": "Water Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Current Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heat_pump_actual_service_water_temperature",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Domestic Hot Water Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "heat_pump_actual_service_water_temperature",
     "legendFormat": "Actual Water Temperature"
    },
    {
     "expr": "heat_pump_target_service_water_temperature",
     "legendFormat": "Target Water Temperature"
    }
   ]
  },
  {
   "title": "Target Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heat_pump_target_service_water_temperature",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  { "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 } }
 ]
}